### ISSUE TITLE
Bookmarklet support

### ISSUE THREAD

**Issue by sandeepravi** [Unknowny/ScrapeMate#1]
I was just curious why the bookmarklet support was removed for this. It does seem to be working as expected right?

Is there anything that is not supported in the bookmarklet?

**Comment by hermit-crab** [comment]
Bookmarklet support was dropped since it would be very hard for me to maintain and develop further (separate build setup, separate way to fire up the script, various adjustments) and certain features were almost impossible also (javascript toggling and having a single global storage for settings and presets). Bookmarklet invocations are also not available at all on certain pages that are configured with restricted CSP `script-src` or such directives (twitter or github for example). This CSP thing is a big one, I do like the bookmarklets myself but this seem to be rendering most of them obsolete.

As for what is not supported, javascript toggling is not reliable on it and no single preset storage. Presets might get wiped if a domain LocalStorage is wiped. I'm not sure under which circumstances it may happen. Might be some other bugfixes or minor things that's been added after the support was dropped.

**Comment by sandeepravi** [comment]
yeah, the CSP is a big issue otherwise bookmarklets would have been simpler even with lesser features.
